### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by daspecster** [taylorotwell/hello-world#6]
I would like to IPv6 supported [here](https://github.com/taylorotwell/hello-world/blob/464e08f8693ca162b4fbcd7585a0403d6cd63211/public/index.php#L3)

Related: https://bugs.php.net/bug.php?id=49493

**Comment by padarom** [comment]
I think this issue can be closed.

The bug you linked is related to `gethostbyname`, the function used in this is `gethostname`. The prior resolves a hostname to an ip address, the latter returns the local hostname. 

This has nothing to do with IPv4 or IPv6 (except if the hostname happens to include either of these).

**Comment by daspecster** [comment]
Agreed. Thank you @padarom.
